version: '3.9'

services:

  bemar-dhcp:
    image: bemar-dhcp:0.1
    restart: always
    ports:
      - "67:67/udp"
    volumes:
      - "bemarDhcpVol:/app/log"
    environment:
      - TZ=Europe/Berlin
      - listeners=eth0:67:bemar.local
      - arp.arp_active=false
      
volumes:
  bemarDhcpVol: